version: '3.1'

services:
  app:
    image: '6083cbeed36288dc8c82e81f27347f500e3c45a7444abe62d71f6aee64e813f2'
    container_name: app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - MONGO_URI=mongodb://mongodb:27017/mongo
    depends_on:
      - db
      - mongodb

  db:
    image: postgres
    expose:
      - '5432'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

  mongodb:
    image: mongo:5.0.3
    container_name: mongodb
    expose:
      - "27017"

